<h1 style="color:blue">Pivot basics</h1>

In [ ]:
# prompt: open shared with me drive

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"D:\Saad Maqbool\New folder\weather.csv")
df

       date      city  temperature  humidity
0  5/1/2024  new york           65        56
1  5/2/2024  new york           66        58
2  5/3/2024  new york           68        60
3  5/1/2024     dubai           75        80
4  5/2/2024     dubai           78        83
5  5/3/2024     dubai           82        85
6  5/1/2024   beijing           80        26
7  5/2/2024   beijing           77        30
8  5/3/2024   beijing           79        35

In [ ]:
df.pivot(index='city',columns='date')

         temperature                   humidity
date        5/1/2024 5/2/2024 5/3/2024 5/1/2024 5/2/2024 5/3/2024
city
beijing           80       77       79       26       30       35
dubai             75       78       82       80       83       85
new york          65       66       68       56       58       60

In [ ]:
df.pivot(index='city',columns='date',values="humidity")

date      5/1/2024  5/2/2024  5/3/2024
city
beijing         26        30        35
dubai           80        83        85
new york        56        58        60

In [ ]:
df.pivot(index='date',columns='city')

         temperature                humidity
city         beijing dubai new york  beijing dubai new york
date
5/1/2024          80    75       65       26    80       56
5/2/2024          77    78       66       30    83       58
5/3/2024          79    82       68       35    85       60

In [ ]:
df.pivot(index='humidity',columns='city')

              date                     temperature
city       beijing     dubai  new york     beijing dubai new york
humidity
26        5/1/2024       NaN       NaN        80.0   NaN      NaN
30        5/2/2024       NaN       NaN        77.0   NaN      NaN
35        5/3/2024       NaN       NaN        79.0   NaN      NaN
56             NaN       NaN  5/1/2024         NaN   NaN     65.0
58             NaN       NaN  5/2/2024         NaN   NaN     66.0
60             NaN       NaN  5/3/2024         NaN   NaN     68.0
80             NaN  5/1/2024       NaN         NaN  75.0      NaN
83             NaN  5/2/2024       NaN         NaN  78.0      NaN
85             NaN  5/3/2024       NaN         NaN  82.0      NaN

<h1 style="color:blue">Pivot Table</h1>

In [2]:
df = pd.read_csv(r"D:\Saad Maqbool\New folder\weather2.csv")
df

       date      city  temperature  humidity
0  5/1/2024  new york           65        56
1  5/1/2024  new york           61        54
2  5/2/2024  new york           70        60
3  5/2/2024  new york           72        62
4  5/1/2024     dubai           75        80
5  5/1/2024     dubai           78        83
6  5/2/2024     dubai           82        85
7  5/2/2024     dubai           80        26

In [3]:
df.pivot_table(index="city",columns="date")

         humidity          temperature
date     5/1/2024 5/2/2024    5/1/2024 5/2/2024
city
dubai        81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

<h2 style="color:brown">Margins</h2>

In [4]:
df.pivot_table(index="city",columns="date", margins=True,aggfunc=np.sum)

         humidity               temperature
date     5/1/2024 5/2/2024  All    5/1/2024 5/2/2024  All
city
dubai         163      111  274         153      162  315
new york      110      122  232         126      142  268
All           273      233  506         279      304  583

<h2 style="color:brown">Grouper</h2>

In [16]:
df = pd.read_csv(r"D:\Saad Maqbool\New folder\weather3.csv")
df

        date      city  temperature  humidity
0   5/1/2024  new york           65        56
1   5/2/2024  new york           61        54
2   5/3/2024  new york           70        60
3  12/1/2024  new york           30        50
4  12/2/2024  new york           28        52
5  12/3/2024  new york           25        51

In [9]:
df['date'] = pd.to_datetime(df['date'])
df

        date      city  temperature  humidity
0 2024-05-01  new york           65        56
1 2024-05-02  new york           61        54
2 2024-05-03  new york           70        60
3 2024-12-01  new york           30        50
4 2024-12-02  new york           28        52
5 2024-12-03  new york           25        51

In [14]:
# Pivot table with monthly grouping
df.pivot_table(index=pd.Grouper(freq='ME', key='date'), columns='city')

             humidity temperature
city         new york    new york
date
2024-05-31  56.666667   65.333333
2024-12-31  51.000000   27.666667

In [19]:
df = df.sort_values('date')

df['temp_rolling_3'] = df['temperature'].rolling(window=3).mean()
df['humidity_rolling_3'] = df['humidity'].rolling(window=3).mean()

df['temp_ema'] = df['temperature'].ewm(span=3).mean()

print("Rolling Averages:")
print(df[['date', 'temperature', 'temp_rolling_3', 'temp_ema']])

Rolling Averages:
        date  temperature  temp_rolling_3   temp_ema
3  12/1/2024           30             NaN  30.000000
4  12/2/2024           28             NaN  28.666667
5  12/3/2024           25       27.666667  26.571429
0   5/1/2024           65       39.333333  47.066667
1   5/2/2024           61       50.333333  54.258065
2   5/3/2024           70       65.333333  62.253968

In [20]:
pivot_complex = df.pivot_table(
    index=pd.Grouper(key='date', freq='M'),
    values=['temperature', 'humidity'],
    aggfunc=['mean', 'max', 'min', 'std', 'count']
).round(2)

print("Monthly Pivot with Multiple Aggregations:")
print(pivot_complex)

ValueError: Invalid frequency: M. Failed to parse with error message: ValueError("'M' is no longer supported for offsets. Please use 'ME' instead.")