## <font color="maroon"><h4 align="center">Handling Missing Data - replace method</font>

In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [5]:
new_df = df.replace(-99999, 87)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           87          7  Sunny
2  1/3/2017           28         87   Snow
3  1/4/2017           87          7      0
4  1/5/2017           32         87   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replacing single value**

**Replacing list with single value**

In [6]:
new_df = df.replace(-99999, value=np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [7]:
new_df = df.replace(to_replace=[-99999,-88888], value=0)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            0          7  Sunny
2  1/3/2017           28          0   Snow
3  1/4/2017            0          7      0
4  1/5/2017           32          0   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [8]:
new_df = df.replace(to_replace=[-99999,-88888], value=67)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           67          7  Sunny
2  1/3/2017           28         67   Snow
3  1/4/2017           67          7      0
4  1/5/2017           32         67   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [10]:
new_df = df.replace(to_replace=["Sunny"], value="cold")
new_df

        day  temperature  windspeed event
0  1/1/2017           32          6  Rain
1  1/2/2017       -99999          7  cold
2  1/3/2017           28     -99999  Snow
3  1/4/2017       -99999          7     0
4  1/5/2017           32     -99999  Rain
5  1/6/2017           31          2  cold
6  1/6/2017           34          5     0

In [15]:
new_df = df.replace(to_replace=["1/1/2017"], value="1/1/2018")
new_df

        day  temperature  windspeed  event
0  1/1/2018           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replacing per column**

In [16]:
new_df = df.replace({
        'temperature': -99999,
        'windspeed': -99999,
        'event': '0'
    }, np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [17]:
new_df = df.replace({
        'temperature': -99999,
        'windspeed': -99999,
        'event': '0'
    }, value= 8)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            8          7  Sunny
2  1/3/2017           28          8   Snow
3  1/4/2017            8          7      8
4  1/5/2017           32          8   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      8

**Replacing by using mapping**

In [18]:
new_df = df.replace({
        -99999: np.nan,
        'no event': 'Sunny',
    })
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [19]:
new_df = df.replace({
        -99999: 'hot',
        'no event': 'Sunny',
    })
new_df

        day temperature windspeed  event
0  1/1/2017          32         6   Rain
1  1/2/2017         hot         7  Sunny
2  1/3/2017          28       hot   Snow
3  1/4/2017         hot         7      0
4  1/5/2017          32       hot   Rain
5  1/6/2017          31         2  Sunny
6  1/6/2017          34         5      0

**Regex**

In [20]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'},'', regex=True)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

**Replacing list with another list**

In [21]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [24]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica'],
    'ID Code' : ['21','22','23','24','25','26'],
})
df

         score  student ID Code
0  exceptional      rob      21
1      average     maya      22
2         good  parthiv      23
3         poor      tom      24
4      average   julian      25
5  exceptional    erica      26

In [26]:
df = pd.DataFrame({
    'ID' : ['101','102','103','104','105'],
    'Name': ['Saad','Ali', 'Hassan','Saeed','Hamza'],
    'student': ['CS', 'AI', 'MBA', 'SE', 'BBA'],
})
df

    ID    Name student
0  101    Saad      CS
1  102     Ali      AI
2  103  Hassan     MBA
3  104   Saeed      SE
4  105   Hamza     BBA

In [32]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [35]:
#Write the code to replace score from strings to numeric, say poor:1, average:2, good: 3, exceptional: 4

df['score'] = df['score'].replace({
    'poor': 1,
    'average': 2,
    'good': 3,
    'exceptional': 4
})
df

  score  student
0     4      rob
1     2     maya
2     3  parthiv
3     1      tom
4     2   julian
5     4    erica