# Week 1 - Day 3 Lab: Data & Matrix Manipulation
In this lab, you'll work with a realistic weather dataset. You'll use **Pandas** to explore and clean the data, and **NumPy** to perform matrix operations.

**Dataset:** `hourly_weather_10_days.csv` (10 days of hourly weather data)

## Step 1: Load the Data
- Use Pandas to load the CSV file
- Display the first few rows
- Check the number of rows and columns

import pandas as pd
df = pd.read_csv('hourly_weather_10_days.csv')

In [2]:
# TODO: Load the data into a DataFrame
import pandas as pd

# Replace the file path if needed
df = pd.read_csv('hourly_weather_10_days.csv')
df.head()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3
2,2023-03-01 02:00:00,15.3,73.3,4.7,NaN,11.1
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8

In [129]:
import pandas as pd

# Replace the file path if needed
df = pd.read_csv('hourly_weather_10_days.csv')
df.tail()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
235,2023-03-10 19:00:00,23.4,67.2,9.9,1016.9,8.2
236,2023-03-10 20:00:00,20.2,NaN,8.2,1013.7,10.3
237,2023-03-10 21:00:00,NaN,71.4,4.5,1001.7,10.7
238,2023-03-10 22:00:00,20.9,79.0,5.0,1017.7,8.9
239,2023-03-10 23:00:00,11.5,NaN,7.3,NaN,12.5

In [132]:
import pandas as pd

# Replace the file path if needed
df = pd.read_csv('hourly_weather_10_days.csv')
print(df)

               timestamp  temperature_C  humidity_%  wind_speed_kmph  \
0    2023-03-01 00:00:00           16.6        74.4              5.7
1    2023-03-01 01:00:00           16.2        78.5              5.0
2    2023-03-01 02:00:00           15.3        73.3              4.7
3    2023-03-01 03:00:00           15.8        72.4              1.3
4    2023-03-01 04:00:00           20.9        70.6              6.8
..                   ...            ...         ...              ...
235  2023-03-10 19:00:00           23.4        67.2              9.9
236  2023-03-10 20:00:00           20.2         NaN              8.2
237  2023-03-10 21:00:00            NaN        71.4              4.5
238  2023-03-10 22:00:00           20.9        79.0              5.0
239  2023-03-10 23:00:00           11.5         NaN              7.3

     pressure_hPa  visibility_km
0          1012.5            9.5
1          1012.1           10.3
2             NaN           11.1
3          1005.0            8.9
4          1016.3            9.8
..            ...            ...
235        1016.9            8.2
236        1013.7           10.3
237        1001.7           10.7
238        1017.7            8.9
239           NaN           12.5

[240 rows x 6 columns]

In [6]:
import pandas as pd

# Replace the file path if needed
df = pd.read_csv('hourly_weather_10_days.csv')
df.head(10)

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3
2,2023-03-01 02:00:00,15.3,73.3,4.7,NaN,11.1
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8
5,2023-03-01 05:00:00,20.8,63.7,NaN,1017.9,10.8
6,2023-03-01 06:00:00,22.8,67.0,11.3,1002.3,9.0
7,2023-03-01 07:00:00,22.5,63.7,12.3,1018.6,10.9
8,2023-03-01 08:00:00,21.2,65.3,13.8,1017.3,10.7
9,2023-03-01 09:00:00,28.2,64.5,10.8,1009.6,11.0

In [7]:
import pandas as pd

# Replace the file path if needed
df = pd.read_csv('hourly_weather_10_days.csv')
df.tail(20)

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
220,2023-03-10 04:00:00,20.0,67.3,9.7,1017.1,10.0
221,2023-03-10 05:00:00,21.8,66.3,10.2,1019.9,8.9
222,2023-03-10 06:00:00,23.3,61.1,9.6,1014.5,9.1
223,2023-03-10 07:00:00,24.4,61.5,11.6,1024.2,10.4
224,2023-03-10 08:00:00,24.1,68.0,13.1,1009.3,10.6
225,2023-03-10 09:00:00,28.5,54.0,11.5,1012.2,10.9
226,2023-03-10 10:00:00,25.8,60.9,15.4,1010.1,11.2
227,2023-03-10 11:00:00,25.3,64.4,16.5,1004.5,11.8
228,2023-03-10 12:00:00,NaN,47.8,17.0,1013.8,11.4
229,2023-03-10 13:00:00,23.7,65.7,15.7,1012.7,9.9
230,2023-03-10 14:00:00,24.0,62.5,14.9,1013.5,9.9
231,2023-03-10 15:00:00,22.7,NaN,14.9,1007.7,8.7
232,2023-03-10 16:00:00,24.2,64.4,12.3,NaN,8.4
233,2023-03-10 17:00:00,22.6,61.8,9.1,1005.7,7.8
234,2023-03-10 18:00:00,21.2,68.4,10.5,1009.7,8.9
235,2023-03-10 19:00:00,23.4,67.2,9.9,1016.9,8.2
236,2023-03-10 20:00:00,20.2,NaN,8.2,1013.7,10.3
237,2023-03-10 21:00:00,NaN,71.4,4.5,1001.7,10.7
238,2023-03-10 22:00:00,20.9,79.0,5.0,1017.7,8.9
239,2023-03-10 23:00:00,11.5,NaN,7.3,NaN,12.5

In [12]:
import pandas as pd

# Replace the file path if needed
df = pd.read_csv('hourly_weather_10_days.csv')
df.columns

Index(['timestamp', 'temperature_C', 'humidity_%', 'wind_speed_kmph',
       'pressure_hPa', 'visibility_km'],
      dtype='object')

In [133]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.shape

(240, 6)

In [15]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.dtypes

timestamp           object
temperature_C      float64
humidity_%         float64
wind_speed_kmph    float64
pressure_hPa       float64
visibility_km      float64
dtype: object

In [128]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.shape

(240, 6)

## Step 2: Basic Exploration
- Check column names and data types
- Display basic statistics using `.describe()`
- Count missing values in each column

In [17]:
# TODO: Explore the DataFrame
print(df.info())
print(df.describe())
print(df.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        240 non-null    object
 1   temperature_C    228 non-null    float64
 2   humidity_%       224 non-null    float64
 3   wind_speed_kmph  226 non-null    float64
 4   pressure_hPa     223 non-null    float64
 5   visibility_km    228 non-null    float64
dtypes: float64(5), object(1)
memory usage: 11.4+ KB
None
       temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
count     228.000000  224.000000       226.000000    223.000000     228.000000
mean       21.315789   66.795982        10.105310   1011.884753       9.989474
std         3.421237    8.190300         3.940668      5.187080       1.022166
min        11.500000   47.800000         1.300000    998.100000       6.800000
25%        18.700000   61.075000         6.625000   1008.900000       9.275000
50%        21.900000   66.300000         9.800000   1012.100000      10.000000
75%        23.925000   72.725000        13.500000   1015.100000      10.700000
max        28.700000   88.100000        17.800000   1027.000000      12.600000
timestamp           0
temperature_C      12
humidity_%         16
wind_speed_kmph    14
pressure_hPa       17
visibility_km      12
dtype: int64

In [18]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        240 non-null    object
 1   temperature_C    228 non-null    float64
 2   humidity_%       224 non-null    float64
 3   wind_speed_kmph  226 non-null    float64
 4   pressure_hPa     223 non-null    float64
 5   visibility_km    228 non-null    float64
dtypes: float64(5), object(1)
memory usage: 11.4+ KB

In [19]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.describe()

       temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
count     228.000000  224.000000       226.000000    223.000000     228.000000
mean       21.315789   66.795982        10.105310   1011.884753       9.989474
std         3.421237    8.190300         3.940668      5.187080       1.022166
min        11.500000   47.800000         1.300000    998.100000       6.800000
25%        18.700000   61.075000         6.625000   1008.900000       9.275000
50%        21.900000   66.300000         9.800000   1012.100000      10.000000
75%        23.925000   72.725000        13.500000   1015.100000      10.700000
max        28.700000   88.100000        17.800000   1027.000000      12.600000

In [25]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.isnull()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,True,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
235,False,False,False,False,False,False
236,False,False,True,False,False,False
237,False,True,False,False,False,False
238,False,False,False,False,False,False
239,False,False,True,False,True,False

In [26]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.isnull().sum()

timestamp           0
temperature_C      12
humidity_%         16
wind_speed_kmph    14
pressure_hPa       17
visibility_km      12
dtype: int64

In [23]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.sample

<bound method NDFrame.sample of                timestamp  temperature_C  humidity_%  wind_speed_kmph  \
0    2023-03-01 00:00:00           16.6        74.4              5.7
1    2023-03-01 01:00:00           16.2        78.5              5.0
2    2023-03-01 02:00:00           15.3        73.3              4.7
3    2023-03-01 03:00:00           15.8        72.4              1.3
4    2023-03-01 04:00:00           20.9        70.6              6.8
..                   ...            ...         ...              ...
235  2023-03-10 19:00:00           23.4        67.2              9.9
236  2023-03-10 20:00:00           20.2         NaN              8.2
237  2023-03-10 21:00:00            NaN        71.4              4.5
238  2023-03-10 22:00:00           20.9        79.0              5.0
239  2023-03-10 23:00:00           11.5         NaN              7.3

     pressure_hPa  visibility_km
0          1012.5            9.5
1          1012.1           10.3
2             NaN           11.1
3          1005.0            8.9
4          1016.3            9.8
..            ...            ...
235        1016.9            8.2
236        1013.7           10.3
237        1001.7           10.7
238        1017.7            8.9
239           NaN           12.5

[240 rows x 6 columns]>

In [24]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.value_counts()

timestamp            temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
2023-03-01 00:00:00  16.6           74.4        5.7              1012.5        9.5              1
2023-03-01 01:00:00  16.2           78.5        5.0              1012.1        10.3             1
2023-03-01 03:00:00  15.8           72.4        1.3              1005.0        8.9              1
2023-03-01 04:00:00  20.9           70.6        6.8              1016.3        9.8              1
2023-03-01 06:00:00  22.8           67.0        11.3             1002.3        9.0              1
                                                                                               ..
2023-03-10 14:00:00  24.0           62.5        14.9             1013.5        9.9              1
2023-03-10 17:00:00  22.6           61.8        9.1              1005.7        7.8              1
2023-03-10 18:00:00  21.2           68.4        10.5             1009.7        8.9              1
2023-03-10 19:00:00  23.4           67.2        9.9              1016.9        8.2              1
2023-03-10 22:00:00  20.9           79.0        5.0              1017.7        8.9              1
Name: count, Length: 176, dtype: int64

## Step 3: Handle Missing Values
- Drop or fill missing values
- Justify your approach (e.g., fill with mean, forward fill, etc.)

In [27]:
# TODO: Fill missing values
# Example: df['column'] = df['column'].fillna(df['column'].mean())

# Fill in your logic here

In [28]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df.dropna()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8
6,2023-03-01 06:00:00,22.8,67.0,11.3,1002.3,9.0
...,...,...,...,...,...,...
230,2023-03-10 14:00:00,24.0,62.5,14.9,1013.5,9.9
233,2023-03-10 17:00:00,22.6,61.8,9.1,1005.7,7.8
234,2023-03-10 18:00:00,21.2,68.4,10.5,1009.7,8.9
235,2023-03-10 19:00:00,23.4,67.2,9.9,1016.9,8.2
238,2023-03-10 22:00:00,20.9,79.0,5.0,1017.7,8.9

In [72]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')

df["humidity_%"] = df["humidity_%"].fillna(df["humidity_%"].median())
print(df.head())

             timestamp  temperature_C  humidity_%  wind_speed_kmph  \
0  2023-03-01 00:00:00           16.6        74.4              5.7
1  2023-03-01 01:00:00           16.2        78.5              5.0
2  2023-03-01 02:00:00           15.3        73.3              4.7
3  2023-03-01 03:00:00           15.8        72.4              1.3
4  2023-03-01 04:00:00           20.9        70.6              6.8

   pressure_hPa  visibility_km
0        1012.5            9.5
1        1012.1           10.3
2           NaN           11.1
3        1005.0            8.9
4        1016.3            9.8

In [74]:
df["pressure_hPa"] = df["pressure_hPa"].fillna(df["pressure_hPa"].mode()[0])
print(df.head())

             timestamp  temperature_C  humidity_%  wind_speed_kmph  \
0  2023-03-01 00:00:00           16.6        74.4              5.7
1  2023-03-01 01:00:00           16.2        78.5              5.0
2  2023-03-01 02:00:00           15.3        73.3              4.7
3  2023-03-01 03:00:00           15.8        72.4              1.3
4  2023-03-01 04:00:00           20.9        70.6              6.8

   pressure_hPa  visibility_km
0        1012.5            9.5
1        1012.1           10.3
2        1009.3           11.1
3        1005.0            8.9
4        1016.3            9.8

In [75]:
df["pressure_hPa"] = df["pressure_hPa"].fillna(df["pressure_hPa"].mean())
print(df.head())

             timestamp  temperature_C  humidity_%  wind_speed_kmph  \
0  2023-03-01 00:00:00           16.6        74.4              5.7
1  2023-03-01 01:00:00           16.2        78.5              5.0
2  2023-03-01 02:00:00           15.3        73.3              4.7
3  2023-03-01 03:00:00           15.8        72.4              1.3
4  2023-03-01 04:00:00           20.9        70.6              6.8

   pressure_hPa  visibility_km
0        1012.5            9.5
1        1012.1           10.3
2        1009.3           11.1
3        1005.0            8.9
4        1016.3            9.8

## Step 4: Data Analysis
- Calculate daily average temperature
- Find max, min, mean for each metric
- Which hour of the day is the most humid on average?

In [77]:
# TODO: Perform analysis
# Use groupby, aggregation, and filtering functions
# Placeholder example:
# df['timestamp'] = pd.to_datetime(df['timestamp'])
# df['hour'] = df['timestamp'].dt.hour
# avg_humidity_by_hour = df.groupby('hour')['humidity_%'].mean()

In [78]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
print(df.head())

             timestamp  temperature_C  humidity_%  wind_speed_kmph  \
0  2023-03-01 00:00:00           16.6        74.4              5.7
1  2023-03-01 01:00:00           16.2        78.5              5.0
2  2023-03-01 02:00:00           15.3        73.3              4.7
3  2023-03-01 03:00:00           15.8        72.4              1.3
4  2023-03-01 04:00:00           20.9        70.6              6.8

   pressure_hPa  visibility_km
0        1012.5            9.5
1        1012.1           10.3
2           NaN           11.1
3        1005.0            8.9
4        1016.3            9.8

In [76]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')

df.drop("timestamp", axis=1, inplace=True)
print(df.head())

   temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
0           16.6        74.4              5.7        1012.5            9.5
1           16.2        78.5              5.0        1012.1           10.3
2           15.3        73.3              4.7           NaN           11.1
3           15.8        72.4              1.3        1005.0            8.9
4           20.9        70.6              6.8        1016.3            9.8

In [80]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')
df['timestamp'] = pd.to_datetime(df['timestamp'])
print(df.head())

            timestamp  temperature_C  humidity_%  wind_speed_kmph  \
0 2023-03-01 00:00:00           16.6        74.4              5.7
1 2023-03-01 01:00:00           16.2        78.5              5.0
2 2023-03-01 02:00:00           15.3        73.3              4.7
3 2023-03-01 03:00:00           15.8        72.4              1.3
4 2023-03-01 04:00:00           20.9        70.6              6.8

   pressure_hPa  visibility_km
0        1012.5            9.5
1        1012.1           10.3
2           NaN           11.1
3        1005.0            8.9
4        1016.3            9.8

In [ ]:
daily_avg = df.groupby(df["timestamp"].dt.date)["temperature_C"].mean()
print(daily_avg)


hourly_humidity = df.groupby(df["timestamp"].dt.hour)["humidity_%"].mean()
print(hourly_humidity)

print("Most humid hour:", hourly_humidity.idxmax())
print(df.describe())

timestamp
2023-03-01    21.260870
2023-03-02    21.256522
2023-03-03    21.304348
2023-03-04    21.430435
2023-03-05    21.539130
2023-03-06    21.858333
2023-03-07    21.173913
2023-03-08    20.895238
2023-03-09    20.769565
2023-03-10    21.622727
Name: temperature_C, dtype: float64
timestamp
0     78.170000
1     78.420000
2     75.414286
3     71.940000
4     69.310000
5     68.611111
6     65.770000
7     65.044444
8     63.490000
9     59.650000
10    58.710000
11    58.910000
12    59.422222
13    58.330000
14    61.366667
15    60.888889
16    59.600000
17    64.030000
18    66.971429
19    69.190000
20    67.488889
21    72.700000
22    73.750000
23    79.100000
Name: humidity_%, dtype: float64
Most humid hour: 23
                 timestamp  temperature_C  humidity_%  wind_speed_kmph  \
count                  240     228.000000  224.000000       226.000000
mean   2023-03-05 23:30:00      21.315789   66.795982        10.105310
min    2023-03-01 00:00:00      11.500000   47.800000         1.300000
25%    2023-03-03 11:45:00      18.700000   61.075000         6.625000
50%    2023-03-05 23:30:00      21.900000   66.300000         9.800000
75%    2023-03-08 11:15:00      23.925000   72.725000        13.500000
max    2023-03-10 23:00:00      28.700000   88.100000        17.800000
std                    NaN       3.421237    8.190300         3.940668

       pressure_hPa  visibility_km
count    223.000000     228.000000
mean    1011.884753       9.989474
min      998.100000       6.800000
25%     1008.900000       9.275000
50%     1012.100000      10.000000
75%     1015.100000      10.700000
max     1027.000000      12.600000
std        5.187080       1.022166

In [82]:
import pandas as pd

df = pd.read_csv('hourly_weather_10_days.csv')

result = df[["humidity_%", "pressure_hPa"]].agg(["max", "min", "mean"])
print(result)

      humidity_%  pressure_hPa
max    88.100000   1027.000000
min    47.800000    998.100000
mean   66.795982   1011.884753

In [ ]:
# just practice for correlation
correlation = df.corr(numeric_only=True)
print(correlation)

                 temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  \
temperature_C         1.000000   -0.637024         0.703787      0.008192
humidity_%           -0.637024    1.000000        -0.727704      0.030638
wind_speed_kmph       0.703787   -0.727704         1.000000     -0.049044
pressure_hPa          0.008192    0.030638        -0.049044      1.000000
visibility_km         0.023312   -0.103234         0.081418     -0.061171

                 visibility_km
temperature_C         0.023312
humidity_%           -0.103234
wind_speed_kmph       0.081418
pressure_hPa         -0.061171
visibility_km         1.000000

## Step 5: NumPy Matrix Exercises
Convert relevant DataFrame columns into NumPy arrays and perform matrix operations.

In [59]:
# TODO: Extract temperature and wind_speed as NumPy arrays
import numpy as np
df = pd.read_csv('hourly_weather_10_days.csv')

temp = df['temperature_C'].to_numpy()
wind = df['wind_speed_kmph'].to_numpy()
print("Temperature array:", temp)
print("Wind speed array:", wind)

Temperature array: [16.6 16.2 15.3 15.8 20.9 20.8 22.8 22.5 21.2 28.2  nan 25.6 25.4 23.4
 27.6 23.8 22.  23.7 23.1 22.1 18.2 19.4 19.7 14.7 15.9 15.7 17.6 20.
 22.  21.2 22.7 21.5 23.6 28.7 20.5 25.1 22.1 24.5 22.6 21.9 23.9  nan
 24.2 22.  19.9 18.8 16.5 18.  13.6 15.7 18.5 15.9 25.7 20.9 20.8 20.7
 22.3 25.7 24.8 21.2 25.5 21.9 22.4 24.7 24.4  nan 23.3 24.4 22.7 20.9
 18.6 15.4 16.7 18.7 17.9 16.  21.5 22.1 27.1 23.7 21.9 24.2 26.8 24.4
  nan 25.7 24.  19.5 23.  23.7 19.8 21.1 18.7 20.8 19.7 15.9 19.7 12.4
 18.7 18.9 21.2 21.  19.6 20.5 24.7  nan 23.3 23.1 22.8 24.5 24.9 24.7
 24.1 22.5 24.2 23.3 22.2 23.9 16.8 18.4 17.8 18.5 21.1 21.9 17.9 16.6
 23.3 24.8 22.5 26.  25.4 24.3 26.2 20.8 21.3 22.7 24.7 23.5 25.6 23.2
 23.9 15.5 19.8 17.3 15.8 17.6 17.9  nan 19.8 23.4 19.9 25.7 23.1 25.9
 24.4 22.5 24.8 24.5 24.2 22.9 20.  20.7 20.5 21.9 23.2 15.4 15.3 17.6
 13.5  nan 17.4 14.8 21.2 18.5 21.6 23.4 26.  22.3  nan 24.9 23.7  nan
 24.6 23.6 25.5 24.4 22.5 21.5 19.  17.3 15.2 17.9 14.3 17.3 15.6 21.5
 17.8 21.2 20.6 21.3 22.8 21.2 25.1 25.7 27.1 25.   nan 23.7 21.5 24.3
 23.6 18.6 19.6 14.7 19.  16.2 17.7 16.3 16.8 17.3 20.  21.8 23.3 24.4
 24.1 28.5 25.8 25.3  nan 23.7 24.  22.7 24.2 22.6 21.2 23.4 20.2  nan
 20.9 11.5]
Wind speed array: [ 5.7  5.   4.7  1.3  6.8  nan 11.3 12.3 13.8 10.8 13.5 17.6 16.  16.5
 12.8 13.8 14.1  nan  8.1  8.   7.3  6.2  4.3  4.6  4.4  7.7  5.3  3.2
  6.2  9.7 11.3 11.  12.8 13.4 16.3 14.1 14.4 12.5 12.7 14.  12.8  nan
  7.6  9.7  8.   6.9  5.9  4.3  6.7  5.5  6.7  6.6  8.4  8.4 10.9 12.8
 10.3 16.7 15.8 17.8 15.1 13.7 13.  16.3 15.2 12.7  nan  8.2  8.4  8.5
  4.7  6.9  7.3  3.2  4.   6.9  5.3  7.8 12.7 12.7  nan 11.3 13.  17.
 15.9 12.8 14.8 14.7 12.  12.2 12.   4.7  6.5  6.4  7.3  8.2  nan  5.
  4.8  6.3  5.5  6.8  7.8 11.9 12.9 15.6 13.3 15.8 15.4 14.1 15.6 12.3
  nan 10.5  9.2  8.7 10.   5.6  7.3  6.   6.   6.6  6.9  9.2  6.6  8.4
  8.5 10.4 10.8 13.3 13.5 14.7 15.  16.3 13.9 12.3 12.6  nan  8.6  nan
  6.4  nan  4.3  3.7  nan  6.6  3.7  8.6  nan  9.   8.3 11.4 11.5 13.6
 15.3 16.2 14.6 14.9 15.  13.6  nan  8.7  7.8  9.5  9.3  5.6  7.3  3.9
  6.2  5.2  5.5  6.4  7.1  8.4  8.1 13.5 11.3 13.8 16.9 13.9 15.3 15.2
 13.6 14.2 10.6 11.3  7.5 11.1  6.5 10.3  3.8  5.7  6.3  4.4  5.4  5.8
  8.9  7.9 11.2  8.8  nan 15.5 17.4 13.5 14.8 17.4 12.2 13.4 15.4 11.
 10.9  6.5  7.8  6.8  4.4  6.3  6.4  5.9  4.5  7.2  9.7 10.2  9.6 11.6
 13.1 11.5 15.4 16.5 17.  15.7 14.9 14.9 12.3  9.1 10.5  9.9  8.2  4.5
  5.   7.3]

In [86]:
temp = df['temperature_C'].to_numpy()
wind = df['wind_speed_kmph'].to_numpy()
 
print(temp.shape)   
print(temp[:6])     #print just first 6 values

(240,)
[16.6 16.2 15.3 15.8 20.9 20.8]

In [ ]:
print("Missing in temp:", np.isnan(temp).sum()) #isnan is used in Numpy #insa is in pandas
print("Missing in wind:", np.isnan(wind).sum())

Missing in temp: 12
Missing in wind: 14

In [ ]:
tempmean = np.nanmean(temp)  
windmean = np.nanmean(wind)

tempclean = np.where(np.isnan(temp), tempmean, temp)
windclean = np.where(np.isnan(wind), windmean, wind)

print("Missing in tempclean:", np.isnan(tempclean).sum())  
print("Missing in windclean:", np.isnan(windclean).sum())

Missing in tempclean: 0
Missing in windclean: 0

In [91]:

weathermatrix = np.column_stack((tempclean, windclean))

print(weathermatrix.shape)  
print(weathermatrix[:5])

(240, 2)
[[16.6  5.7]
 [16.2  5. ]
 [15.3  4.7]
 [15.8  1.3]
 [20.9  6.8]]

### a) Reshape into matrix form
- Assume each row is a day
- Reshape temperature into a (10, 24) matrix
- Calculate daily min, max, and mean using axis-based operations

In [92]:
# TODO: Reshape and aggregate
# Hint: temp_matrix = temp.reshape((10, 24))
# Write functions to find min, max, mean across rows

In [94]:
print("Total temp readings:", tempclean.shape[0])

Total temp readings: 240

In [97]:
# Reshape: 10 days, 24 hours per day
tempmatrix = tempclean.reshape(10, 24)

print(tempmatrix.shape)   
print(tempmatrix[0])      
print(tempmatrix[1])

(10, 24)
[16.6        16.2        15.3        15.8        20.9        20.8
 22.8        22.5        21.2        28.2        21.31578947 25.6
 25.4        23.4        27.6        23.8        22.         23.7
 23.1        22.1        18.2        19.4        19.7        14.7       ]
[15.9        15.7        17.6        20.         22.         21.2
 22.7        21.5        23.6        28.7        20.5        25.1
 22.1        24.5        22.6        21.9        23.9        21.31578947
 24.2        22.         19.9        18.8        16.5        18.        ]

In [100]:
daily_min  = temp_matrix.min(axis=1)
daily_max  = temp_matrix.max(axis=1)
daily_mean = temp_matrix.mean(axis=1)

for day in range(6):
    print(f"Day {day+1}: min={daily_min[day]:.1f}, max={daily_max[day]:.1f}, mean={daily_mean[day]:.1f}")

Day 1: min=nan, max=nan, mean=nan
Day 2: min=nan, max=nan, mean=nan
Day 3: min=nan, max=nan, mean=nan
Day 4: min=nan, max=nan, mean=nan
Day 5: min=nan, max=nan, mean=nan
Day 6: min=15.5, max=26.2, mean=21.9

In [63]:
import numpy as np

temp = df['temperature_C'].values
assert temp.size == 240

temp_matrix = temp.reshape((10, 24))

daily_min = np.nanmin(temp_matrix, axis=1)
daily_max = np.nanmax(temp_matrix, axis=1)
daily_mean = np.nanmean(temp_matrix, axis=1)

for day in range(10):
    print(f"Day {day+1}: min={daily_min[day]:.1f}°C, max={daily_max[day]:.1f}°C, mean={daily_mean[day]:.2f}°C")

Day 1: min=14.7°C, max=28.2°C, mean=21.26°C
Day 2: min=15.7°C, max=28.7°C, mean=21.26°C
Day 3: min=13.6°C, max=25.7°C, mean=21.30°C
Day 4: min=15.9°C, max=27.1°C, mean=21.43°C
Day 5: min=12.4°C, max=24.9°C, mean=21.54°C
Day 6: min=15.5°C, max=26.2°C, mean=21.86°C
Day 7: min=15.3°C, max=25.9°C, mean=21.17°C
Day 8: min=13.5°C, max=26.0°C, mean=20.90°C
Day 9: min=14.3°C, max=27.1°C, mean=20.77°C
Day 10: min=11.5°C, max=28.5°C, mean=21.62°C

### b) Normalize the temperature matrix
- Subtract the mean and divide by std deviation
- Do it manually using NumPy functions

In [102]:
# TODO: Normalize temp_matrix
# Placeholder for function: def normalize(matrix):
# return ...

# Apply it to temp_matrix

In [105]:
def normalize(matrix):
    mean = np.nanmean(matrix)
    std = np.nanstd(matrix)
    return (matrix - mean) / std

normalized_temp = normalize(temp_matrix)
print("New mean (should be ~0):", normalized_temp.mean())
print("New std (should be ~1):", normalized_temp.std())

New mean (should be ~0): nan
New std (should be ~1): nan

In [110]:
row_mean = temp_matrix.mean(axis=1, keepdims=True)  # shape (10, 1)
row_std  = temp_matrix.std(axis=1, keepdims=True)   # shape (10, 1)

temp_normalized_per_day = (temp_matrix - row_mean) / row_std

print(temp_normalized_per_day[0].mean())

nan

In [66]:
def normalize(matrix):
    mean = np.nanmean(matrix)
    std = np.nanstd(matrix)
    return (matrix - mean) / std

normalized_temp = normalize(temp_matrix)

print(normalized_temp)
print("Mean:", np.nanmean(normalized_temp))
print("Std:", np.nanstd(normalized_temp))

[[-1.38142018 -1.49859422 -1.76223579 -1.61576825 -0.12179932 -0.15109283
   0.43477733  0.34689681 -0.0339188   2.01662679         nan  1.25499557
   1.19640855  0.61053838  1.84086574  0.72771242  0.20042927  0.69841891
   0.52265786  0.22972278 -0.91272405 -0.56120195 -0.47332142 -1.93799684]
 [-1.58647474 -1.64506176 -1.0884851  -0.3854409   0.20042927 -0.0339188
   0.40548383  0.05396173  0.6691254   2.16309433 -0.23897336  1.10852803
   0.22972278  0.93276698  0.37619032  0.17113576  0.75700593         nan
   0.84488645  0.20042927 -0.41473441 -0.736963   -1.41071369 -0.97131107]
 [-2.26022543 -1.64506176 -0.82484352 -1.58647474  1.28428908 -0.12179932
  -0.15109283 -0.18038634  0.28830979  1.28428908  1.0206475  -0.0339188
   1.22570206  0.17113576  0.3176033   0.99135399  0.90347347         nan
   0.58124488  0.90347347  0.40548383 -0.12179932 -0.79555002 -1.73294228]
 [-1.35212667 -0.76625651 -1.00060457 -1.55718123  0.05396173  0.22972278
   1.69439819  0.69841891  0.17113576  0.84488645  1.60651767  0.90347347
          nan  1.28428908  0.78629943 -0.53190844  0.49336435  0.69841891
  -0.44402792 -0.06321231 -0.76625651 -0.15109283 -0.47332142 -1.58647474]
 [-0.47332142 -2.61174753 -0.76625651 -0.70766949 -0.0339188  -0.09250582
  -0.50261493 -0.23897336  0.99135399         nan  0.58124488  0.52265786
   0.43477733  0.93276698  1.04994101  0.99135399  0.81559294  0.34689681
   0.84488645  0.58124488  0.25901628  0.75700593 -1.32283317 -0.85413703]
 [-1.02989808 -0.82484352 -0.06321231  0.17113576 -1.00060457 -1.38142018
   0.58124488  1.0206475   0.34689681  1.3721696   1.19640855  0.87417996
   1.43075662 -0.15109283 -0.00462529  0.40548383  0.99135399  0.63983189
   1.25499557  0.55195137  0.75700593 -1.70364877 -0.44402792 -1.17636562]
 [-1.61576825 -1.0884851  -1.00060457         nan -0.44402792  0.61053838
  -0.41473441  1.28428908  0.52265786  1.34287609  0.90347347  0.34689681
   1.0206475   0.93276698  0.84488645  0.46407084 -0.3854409  -0.18038634
  -0.23897336  0.17113576  0.55195137 -1.73294228 -1.76223579 -1.0884851 ]
 [-2.28951894         nan -1.14707212 -1.90870333 -0.0339188  -0.82484352
   0.08325523  0.61053838  1.3721696   0.28830979         nan  1.04994101
   0.69841891         nan  0.96206048  0.6691254   1.22570206  0.90347347
   0.34689681  0.05396173 -0.67837598 -1.17636562 -1.7915293  -1.00060457]
 [-2.05517088 -1.17636562 -1.67435527  0.05396173 -1.02989808 -0.0339188
  -0.20967985 -0.00462529  0.43477733 -0.0339188   1.10852803  1.28428908
   1.69439819  1.07923452         nan  0.69841891  0.05396173  0.87417996
   0.6691254  -0.79555002 -0.50261493 -1.93799684 -0.67837598 -1.49859422]
 [-1.05919159 -1.46930071 -1.32283317 -1.17636562 -0.3854409   0.14184225
   0.58124488  0.90347347  0.81559294  2.10450731  1.31358258  1.16711504
          nan  0.69841891  0.78629943  0.40548383  0.84488645  0.37619032
  -0.0339188   0.61053838 -0.32685388         nan -0.12179932 -2.87538911]]
Mean: 4.733056052349352e-16
Std: 1.0

### c) Apply custom mask/filter
- Create a mask for wind speed > 15 kmph
- Use it to extract high-wind readings

In [120]:
# TODO: Create boolean mask and filter wind speeds
# mask = wind > 15
# high_wind = wind[mask]

In [121]:
import pandas as pd
import numpy as np

df = pd.read_csv('hourly_weather_10_days.csv')

# Step 2: Extract as arrays
temp = df['temperature_C'].to_numpy()
wind = df['wind_speed_kmph'].to_numpy()

# Step 4: Clean NaNs
temp_mean = np.nanmean(temp)
wind_mean = np.nanmean(wind)
temp_clean = np.where(np.isnan(temp), temp_mean, temp)
wind_clean = np.where(np.isnan(wind), wind_mean, wind)

print("wind_clean defined:", wind_clean.shape)

wind_clean defined: (240,)

In [122]:
high_wind_mask = wind_clean > 15
print(high_wind_mask.shape)
print(high_wind_mask[:10])
print(type(high_wind_mask))

(240,)
[False False False False False False False False False False]
<class 'numpy.ndarray'>

In [68]:
wind = df['wind_speed_kmph'].values

mask = wind > 15
high_wind = wind[mask]

print("Mask:", mask)
print("High wind readings:", high_wind)
print("Count:", high_wind.size)

Mask: [False False False False False False False False False False False  True
  True  True False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False  True  True  True
  True False False  True  True False False False False False False False
 False False False False False False False False False False False  True
  True False False False False False False False False False False False
 False False False False False False False False False  True False  True
  True False  True False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
  True  True False False False False False False False False False False
 False False False False False False False False False  True  True False
 False  True False False  True False False False False False False False
 False False False False False False False False False False  True  True
  True  True False False False False False False False False False False]
High wind readings: [17.6 16.  16.5 16.3 16.7 15.8 17.8 15.1 16.3 15.2 17.  15.9 15.6 15.8
 15.4 15.6 16.3 15.3 16.2 16.9 15.3 15.2 15.5 17.4 17.4 15.4 15.4 16.5
 17.  15.7]
Count: 30

## Final Challenge: Write Your Own Function
Write a function `daily_summary(matrix)` that takes a NumPy matrix of shape (10, 24) and returns a summary dictionary for each day.

In [135]:
# TODO: Write and test your function
def daily_summary(matrix):
    # return list of dicts with min, max, mean
    pass

# Example usage:
# summaries = daily_summary(temp_matrix)

In [136]:
import pandas as pd
import numpy as np

df = pd.read_csv('hourly_weather_10_days.csv')
print(df.shape)

(240, 6)

In [158]:
def daily_summary_multi(df, n_hours_per_day=24):
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    n_rows = df.shape[0]

    if n_rows % n_hours_per_day != 0:
        raise ValueError(f"Row count ({n_rows}) is not divisible by {n_hours_per_day}")

    n_days = n_rows // n_hours_per_day
    summaries = []

    for day in range(n_days):
        start = day * n_hours_per_day
        end = start + n_hours_per_day
        day_df = df.iloc[start:end]

        day_summary = {"day": day + 1}

        for col in numeric_cols:
            values = day_df[col].to_numpy()
            day_summary[f"{col}_min"] = round(float(np.nanmin(values)), 2)
            day_summary[f"{col}_max"] = round(float(np.nanmax(values)), 2)
            day_summary[f"{col}_mean"] = round(float(np.nanmean(values)), 2)

        summaries.append(day_summary)

    return summaries


summaries = daily_summary_multi(df)
#for 2 value print 
for s in summaries[:2]:
    print(s)

{'day': 1, 'temperature_C_min': 14.7, 'temperature_C_max': 28.2, 'temperature_C_mean': 21.26, 'humidity_%_min': 50.7, 'humidity_%_max': 78.5, 'humidity_%_mean': 66.28, 'wind_speed_kmph_min': 1.3, 'wind_speed_kmph_max': 17.6, 'wind_speed_kmph_mean': 9.75, 'pressure_hPa_min': 1002.3, 'pressure_hPa_max': 1022.9, 'pressure_hPa_mean': 1012.46, 'visibility_km_min': 8.9, 'visibility_km_max': 11.5, 'visibility_km_mean': 10.27}
{'day': 2, 'temperature_C_min': 15.7, 'temperature_C_max': 28.7, 'temperature_C_mean': 21.26, 'humidity_%_min': 51.8, 'humidity_%_max': 83.2, 'humidity_%_mean': 66.95, 'wind_speed_kmph_min': 3.2, 'wind_speed_kmph_max': 16.3, 'wind_speed_kmph_mean': 9.75, 'pressure_hPa_min': 999.8, 'pressure_hPa_max': 1024.1, 'pressure_hPa_mean': 1011.78, 'visibility_km_min': 8.0, 'visibility_km_max': 11.8, 'visibility_km_mean': 10.03}

In [159]:
summaries = daily_summary_multi(df)
#for 2 value print 
for s in summaries[:10]:
    print(s)

{'day': 1, 'temperature_C_min': 14.7, 'temperature_C_max': 28.2, 'temperature_C_mean': 21.26, 'humidity_%_min': 50.7, 'humidity_%_max': 78.5, 'humidity_%_mean': 66.28, 'wind_speed_kmph_min': 1.3, 'wind_speed_kmph_max': 17.6, 'wind_speed_kmph_mean': 9.75, 'pressure_hPa_min': 1002.3, 'pressure_hPa_max': 1022.9, 'pressure_hPa_mean': 1012.46, 'visibility_km_min': 8.9, 'visibility_km_max': 11.5, 'visibility_km_mean': 10.27}
{'day': 2, 'temperature_C_min': 15.7, 'temperature_C_max': 28.7, 'temperature_C_mean': 21.26, 'humidity_%_min': 51.8, 'humidity_%_max': 83.2, 'humidity_%_mean': 66.95, 'wind_speed_kmph_min': 3.2, 'wind_speed_kmph_max': 16.3, 'wind_speed_kmph_mean': 9.75, 'pressure_hPa_min': 999.8, 'pressure_hPa_max': 1024.1, 'pressure_hPa_mean': 1011.78, 'visibility_km_min': 8.0, 'visibility_km_max': 11.8, 'visibility_km_mean': 10.03}
{'day': 3, 'temperature_C_min': 13.6, 'temperature_C_max': 25.7, 'temperature_C_mean': 21.3, 'humidity_%_min': 50.0, 'humidity_%_max': 78.8, 'humidity_%_mean': 66.82, 'wind_speed_kmph_min': 4.7, 'wind_speed_kmph_max': 17.8, 'wind_speed_kmph_mean': 10.84, 'pressure_hPa_min': 1007.2, 'pressure_hPa_max': 1027.0, 'pressure_hPa_mean': 1013.2, 'visibility_km_min': 8.8, 'visibility_km_max': 11.5, 'visibility_km_mean': 10.14}
{'day': 4, 'temperature_C_min': 15.9, 'temperature_C_max': 27.1, 'temperature_C_mean': 21.43, 'humidity_%_min': 54.0, 'humidity_%_max': 88.1, 'humidity_%_mean': 67.17, 'wind_speed_kmph_min': 3.2, 'wind_speed_kmph_max': 17.0, 'wind_speed_kmph_mean': 9.94, 'pressure_hPa_min': 1003.4, 'pressure_hPa_max': 1023.8, 'pressure_hPa_mean': 1013.4, 'visibility_km_min': 6.8, 'visibility_km_max': 11.8, 'visibility_km_mean': 9.76}
{'day': 5, 'temperature_C_min': 12.4, 'temperature_C_max': 24.9, 'temperature_C_mean': 21.54, 'humidity_%_min': 52.4, 'humidity_%_max': 82.3, 'humidity_%_mean': 66.46, 'wind_speed_kmph_min': 4.8, 'wind_speed_kmph_max': 15.8, 'wind_speed_kmph_mean': 10.02, 'pressure_hPa_min': 1004.2, 'pressure_hPa_max': 1019.7, 'pressure_hPa_mean': 1011.82, 'visibility_km_min': 8.3, 'visibility_km_max': 12.6, 'visibility_km_mean': 10.06}
{'day': 6, 'temperature_C_min': 15.5, 'temperature_C_max': 26.2, 'temperature_C_mean': 21.86, 'humidity_%_min': 53.1, 'humidity_%_max': 82.1, 'humidity_%_mean': 67.9, 'wind_speed_kmph_min': 3.7, 'wind_speed_kmph_max': 16.3, 'wind_speed_kmph_mean': 9.9, 'pressure_hPa_min': 1003.6, 'pressure_hPa_max': 1019.0, 'pressure_hPa_mean': 1011.71, 'visibility_km_min': 8.1, 'visibility_km_max': 12.4, 'visibility_km_mean': 9.78}
{'day': 7, 'temperature_C_min': 15.3, 'temperature_C_max': 25.9, 'temperature_C_mean': 21.17, 'humidity_%_min': 53.9, 'humidity_%_max': 80.8, 'humidity_%_mean': 65.53, 'wind_speed_kmph_min': 3.7, 'wind_speed_kmph_max': 16.2, 'wind_speed_kmph_mean': 10.21, 'pressure_hPa_min': 998.1, 'pressure_hPa_max': 1017.9, 'pressure_hPa_mean': 1010.51, 'visibility_km_min': 9.0, 'visibility_km_max': 11.3, 'visibility_km_mean': 10.07}
{'day': 8, 'temperature_C_min': 13.5, 'temperature_C_max': 26.0, 'temperature_C_mean': 20.9, 'humidity_%_min': 49.9, 'humidity_%_max': 83.3, 'humidity_%_mean': 67.29, 'wind_speed_kmph_min': 3.8, 'wind_speed_kmph_max': 16.9, 'wind_speed_kmph_mean': 10.06, 'pressure_hPa_min': 1002.7, 'pressure_hPa_max': 1019.2, 'pressure_hPa_mean': 1010.48, 'visibility_km_min': 7.9, 'visibility_km_max': 11.6, 'visibility_km_mean': 9.63}
{'day': 9, 'temperature_C_min': 14.3, 'temperature_C_max': 27.1, 'temperature_C_mean': 20.77, 'humidity_%_min': 51.8, 'humidity_%_max': 86.6, 'humidity_%_mean': 67.14, 'wind_speed_kmph_min': 4.4, 'wind_speed_kmph_max': 17.4, 'wind_speed_kmph_mean': 10.09, 'pressure_hPa_min': 1000.2, 'pressure_hPa_max': 1022.8, 'pressure_hPa_mean': 1011.71, 'visibility_km_min': 8.1, 'visibility_km_max': 11.9, 'visibility_km_mean': 10.04}
{'day': 10, 'temperature_C_min': 11.5, 'temperature_C_max': 28.5, 'temperature_C_mean': 21.62, 'humidity_%_min': 47.8, 'humidity_%_max': 80.1, 'humidity_%_mean': 66.4, 'wind_speed_kmph_min': 4.5, 'wind_speed_kmph_max': 17.0, 'wind_speed_kmph_mean': 10.45, 'pressure_hPa_min': 1000.1, 'pressure_hPa_max': 1024.2, 'pressure_hPa_mean': 1011.67, 'visibility_km_min': 7.8, 'visibility_km_max': 12.5, 'visibility_km_mean': 10.1}

In [161]:
import pandas as pd
import numpy as np

df = pd.read_csv('hourly_weather_10_days.csv')

# if rename the column want 
column_rename = {
    "temperature_C": "temp",
    "humidity_%": "humidity",
    "wind_speed_kmph": "wind",
    "pressure_hPa": "pressure",
    "visibility_km": "visibility"
}

In [162]:
def daily_summary_multi(df, column_rename, n_hours_per_day=24):
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    n_rows = df.shape[0]
    if n_rows % n_hours_per_day != 0:
        raise ValueError(f"Row count ({n_rows}) is not divisible by {n_hours_per_day}.")
    n_days = n_rows // n_hours_per_day
    summaries = []
    for day in range(n_days):
        start = day * n_hours_per_day
        end = start + n_hours_per_day
        day_df = df.iloc[start:end]
        day_summary = {"day": day + 1}
        for col in numeric_cols:
            short_name = column_rename.get(col, col)
            values = day_df[col].to_numpy()
            day_summary[f"{short_name}_min"] = round(float(np.nanmin(values)), 2)
            day_summary[f"{short_name}_max"] = round(float(np.nanmax(values)), 2)
            day_summary[f"{short_name}_mean"] = round(float(np.nanmean(values)), 2)
        summaries.append(day_summary)
    return summaries

In [163]:
summaries = daily_summary_multi(df, column_rename)

for s in summaries:
    print(s)

{'day': 1, 'temp_min': 14.7, 'temp_max': 28.2, 'temp_mean': 21.26, 'humidity_min': 50.7, 'humidity_max': 78.5, 'humidity_mean': 66.28, 'wind_min': 1.3, 'wind_max': 17.6, 'wind_mean': 9.75, 'pressure_min': 1002.3, 'pressure_max': 1022.9, 'pressure_mean': 1012.46, 'visibility_min': 8.9, 'visibility_max': 11.5, 'visibility_mean': 10.27}
{'day': 2, 'temp_min': 15.7, 'temp_max': 28.7, 'temp_mean': 21.26, 'humidity_min': 51.8, 'humidity_max': 83.2, 'humidity_mean': 66.95, 'wind_min': 3.2, 'wind_max': 16.3, 'wind_mean': 9.75, 'pressure_min': 999.8, 'pressure_max': 1024.1, 'pressure_mean': 1011.78, 'visibility_min': 8.0, 'visibility_max': 11.8, 'visibility_mean': 10.03}
{'day': 3, 'temp_min': 13.6, 'temp_max': 25.7, 'temp_mean': 21.3, 'humidity_min': 50.0, 'humidity_max': 78.8, 'humidity_mean': 66.82, 'wind_min': 4.7, 'wind_max': 17.8, 'wind_mean': 10.84, 'pressure_min': 1007.2, 'pressure_max': 1027.0, 'pressure_mean': 1013.2, 'visibility_min': 8.8, 'visibility_max': 11.5, 'visibility_mean': 10.14}
{'day': 4, 'temp_min': 15.9, 'temp_max': 27.1, 'temp_mean': 21.43, 'humidity_min': 54.0, 'humidity_max': 88.1, 'humidity_mean': 67.17, 'wind_min': 3.2, 'wind_max': 17.0, 'wind_mean': 9.94, 'pressure_min': 1003.4, 'pressure_max': 1023.8, 'pressure_mean': 1013.4, 'visibility_min': 6.8, 'visibility_max': 11.8, 'visibility_mean': 9.76}
{'day': 5, 'temp_min': 12.4, 'temp_max': 24.9, 'temp_mean': 21.54, 'humidity_min': 52.4, 'humidity_max': 82.3, 'humidity_mean': 66.46, 'wind_min': 4.8, 'wind_max': 15.8, 'wind_mean': 10.02, 'pressure_min': 1004.2, 'pressure_max': 1019.7, 'pressure_mean': 1011.82, 'visibility_min': 8.3, 'visibility_max': 12.6, 'visibility_mean': 10.06}
{'day': 6, 'temp_min': 15.5, 'temp_max': 26.2, 'temp_mean': 21.86, 'humidity_min': 53.1, 'humidity_max': 82.1, 'humidity_mean': 67.9, 'wind_min': 3.7, 'wind_max': 16.3, 'wind_mean': 9.9, 'pressure_min': 1003.6, 'pressure_max': 1019.0, 'pressure_mean': 1011.71, 'visibility_min': 8.1, 'visibility_max': 12.4, 'visibility_mean': 9.78}
{'day': 7, 'temp_min': 15.3, 'temp_max': 25.9, 'temp_mean': 21.17, 'humidity_min': 53.9, 'humidity_max': 80.8, 'humidity_mean': 65.53, 'wind_min': 3.7, 'wind_max': 16.2, 'wind_mean': 10.21, 'pressure_min': 998.1, 'pressure_max': 1017.9, 'pressure_mean': 1010.51, 'visibility_min': 9.0, 'visibility_max': 11.3, 'visibility_mean': 10.07}
{'day': 8, 'temp_min': 13.5, 'temp_max': 26.0, 'temp_mean': 20.9, 'humidity_min': 49.9, 'humidity_max': 83.3, 'humidity_mean': 67.29, 'wind_min': 3.8, 'wind_max': 16.9, 'wind_mean': 10.06, 'pressure_min': 1002.7, 'pressure_max': 1019.2, 'pressure_mean': 1010.48, 'visibility_min': 7.9, 'visibility_max': 11.6, 'visibility_mean': 9.63}
{'day': 9, 'temp_min': 14.3, 'temp_max': 27.1, 'temp_mean': 20.77, 'humidity_min': 51.8, 'humidity_max': 86.6, 'humidity_mean': 67.14, 'wind_min': 4.4, 'wind_max': 17.4, 'wind_mean': 10.09, 'pressure_min': 1000.2, 'pressure_max': 1022.8, 'pressure_mean': 1011.71, 'visibility_min': 8.1, 'visibility_max': 11.9, 'visibility_mean': 10.04}
{'day': 10, 'temp_min': 11.5, 'temp_max': 28.5, 'temp_mean': 21.62, 'humidity_min': 47.8, 'humidity_max': 80.1, 'humidity_mean': 66.4, 'wind_min': 4.5, 'wind_max': 17.0, 'wind_mean': 10.45, 'pressure_min': 1000.1, 'pressure_max': 1024.2, 'pressure_mean': 1011.67, 'visibility_min': 7.8, 'visibility_max': 12.5, 'visibility_mean': 10.1}

In [164]:
summary_df = pd.DataFrame(summaries)
print(summary_df)

   day  temp_min  temp_max  temp_mean  humidity_min  humidity_max  \
0    1      14.7      28.2      21.26          50.7          78.5
1    2      15.7      28.7      21.26          51.8          83.2
2    3      13.6      25.7      21.30          50.0          78.8
3    4      15.9      27.1      21.43          54.0          88.1
4    5      12.4      24.9      21.54          52.4          82.3
5    6      15.5      26.2      21.86          53.1          82.1
6    7      15.3      25.9      21.17          53.9          80.8
7    8      13.5      26.0      20.90          49.9          83.3
8    9      14.3      27.1      20.77          51.8          86.6
9   10      11.5      28.5      21.62          47.8          80.1

   humidity_mean  wind_min  wind_max  wind_mean  pressure_min  pressure_max  \
0          66.28       1.3      17.6       9.75        1002.3        1022.9
1          66.95       3.2      16.3       9.75         999.8        1024.1
2          66.82       4.7      17.8      10.84        1007.2        1027.0
3          67.17       3.2      17.0       9.94        1003.4        1023.8
4          66.46       4.8      15.8      10.02        1004.2        1019.7
5          67.90       3.7      16.3       9.90        1003.6        1019.0
6          65.53       3.7      16.2      10.21         998.1        1017.9
7          67.29       3.8      16.9      10.06        1002.7        1019.2
8          67.14       4.4      17.4      10.09        1000.2        1022.8
9          66.40       4.5      17.0      10.45        1000.1        1024.2

   pressure_mean  visibility_min  visibility_max  visibility_mean
0        1012.46             8.9            11.5            10.27
1        1011.78             8.0            11.8            10.03
2        1013.20             8.8            11.5            10.14
3        1013.40             6.8            11.8             9.76
4        1011.82             8.3            12.6            10.06
5        1011.71             8.1            12.4             9.78
6        1010.51             9.0            11.3            10.07
7        1010.48             7.9            11.6             9.63
8        1011.71             8.1            11.9            10.04
9        1011.67             7.8            12.5            10.10

In [154]:
import pandas as pd

summary_df = pd.DataFrame(summaries)

# List of features you want separate tables for
features = ["temp", "humidity", "wind", "pressure", "visibility"]

# Build a dictionary of DataFrames — one per feature
feature_tables = {}

for feature in features:
    cols = ["day", f"{feature}_min", f"{feature}_max", f"{feature}_mean"]
    feature_tables[feature] = summary_df[cols]

In [155]:
for feature, table in feature_tables.items():
    print(f"\n===== {feature.upper()} =====")
    print(table.to_string(index=False))

===== TEMP =====
 day  temp_min  temp_max  temp_mean
   1      14.7      28.2      21.26
   2      15.7      28.7      21.26
   3      13.6      25.7      21.30
   4      15.9      27.1      21.43
   5      12.4      24.9      21.54
   6      15.5      26.2      21.86
   7      15.3      25.9      21.17
   8      13.5      26.0      20.90
   9      14.3      27.1      20.77
  10      11.5      28.5      21.62

===== HUMIDITY =====
 day  humidity_min  humidity_max  humidity_mean
   1          50.7          78.5          66.28
   2          51.8          83.2          66.95
   3          50.0          78.8          66.82
   4          54.0          88.1          67.17
   5          52.4          82.3          66.46
   6          53.1          82.1          67.90
   7          53.9          80.8          65.53
   8          49.9          83.3          67.29
   9          51.8          86.6          67.14
  10          47.8          80.1          66.40

===== WIND =====
 day  wind_min  wind_max  wind_mean
   1       1.3      17.6       9.75
   2       3.2      16.3       9.75
   3       4.7      17.8      10.84
   4       3.2      17.0       9.94
   5       4.8      15.8      10.02
   6       3.7      16.3       9.90
   7       3.7      16.2      10.21
   8       3.8      16.9      10.06
   9       4.4      17.4      10.09
  10       4.5      17.0      10.45

===== PRESSURE =====
 day  pressure_min  pressure_max  pressure_mean
   1        1002.3        1022.9        1012.46
   2         999.8        1024.1        1011.78
   3        1007.2        1027.0        1013.20
   4        1003.4        1023.8        1013.40
   5        1004.2        1019.7        1011.82
   6        1003.6        1019.0        1011.71
   7         998.1        1017.9        1010.51
   8        1002.7        1019.2        1010.48
   9        1000.2        1022.8        1011.71
  10        1000.1        1024.2        1011.67

===== VISIBILITY =====
 day  visibility_min  visibility_max  visibility_mean
   1             8.9            11.5            10.27
   2             8.0            11.8            10.03
   3             8.8            11.5            10.14
   4             6.8            11.8             9.76
   5             8.3            12.6            10.06
   6             8.1            12.4             9.78
   7             9.0            11.3            10.07
   8             7.9            11.6             9.63
   9             8.1            11.9            10.04
  10             7.8            12.5            10.10

In [165]:
def daily_summary(matrix):
    """
    Summarize daily statistics from an hourly readings matrix.

    Parameters
    ----------
    matrix : np.ndarray
        Shape (n_days, 24) — hourly readings per day.

    Returns
    -------
    list[dict]
        One dict per day: {"day": int, "min": float, "max": float, "mean": float}
    """
    if matrix.ndim != 2 or matrix.shape[1] != 24:
        raise ValueError(f"Expected shape (n_days, 24), got {matrix.shape}")

    n_days = matrix.shape[0]
    summaries = []

    for day in range(n_days):
        day_data = matrix[day]

        summaries.append({
            "day": day + 1,
            "min": round(float(day_data.min()), 2),
            "max": round(float(day_data.max()), 2),
            "mean": round(float(day_data.mean()), 2)
        })

    return summaries
    summaries = daily_summary(temp_matrix)

for s in summaries:
    print(s)

{'day': 1, 'temp_min': 14.7, 'temp_max': 28.2, 'temp_mean': 21.26, 'humidity_min': 50.7, 'humidity_max': 78.5, 'humidity_mean': 66.28, 'wind_min': 1.3, 'wind_max': 17.6, 'wind_mean': 9.75, 'pressure_min': 1002.3, 'pressure_max': 1022.9, 'pressure_mean': 1012.46, 'visibility_min': 8.9, 'visibility_max': 11.5, 'visibility_mean': 10.27}
{'day': 2, 'temp_min': 15.7, 'temp_max': 28.7, 'temp_mean': 21.26, 'humidity_min': 51.8, 'humidity_max': 83.2, 'humidity_mean': 66.95, 'wind_min': 3.2, 'wind_max': 16.3, 'wind_mean': 9.75, 'pressure_min': 999.8, 'pressure_max': 1024.1, 'pressure_mean': 1011.78, 'visibility_min': 8.0, 'visibility_max': 11.8, 'visibility_mean': 10.03}
{'day': 3, 'temp_min': 13.6, 'temp_max': 25.7, 'temp_mean': 21.3, 'humidity_min': 50.0, 'humidity_max': 78.8, 'humidity_mean': 66.82, 'wind_min': 4.7, 'wind_max': 17.8, 'wind_mean': 10.84, 'pressure_min': 1007.2, 'pressure_max': 1027.0, 'pressure_mean': 1013.2, 'visibility_min': 8.8, 'visibility_max': 11.5, 'visibility_mean': 10.14}
{'day': 4, 'temp_min': 15.9, 'temp_max': 27.1, 'temp_mean': 21.43, 'humidity_min': 54.0, 'humidity_max': 88.1, 'humidity_mean': 67.17, 'wind_min': 3.2, 'wind_max': 17.0, 'wind_mean': 9.94, 'pressure_min': 1003.4, 'pressure_max': 1023.8, 'pressure_mean': 1013.4, 'visibility_min': 6.8, 'visibility_max': 11.8, 'visibility_mean': 9.76}
{'day': 5, 'temp_min': 12.4, 'temp_max': 24.9, 'temp_mean': 21.54, 'humidity_min': 52.4, 'humidity_max': 82.3, 'humidity_mean': 66.46, 'wind_min': 4.8, 'wind_max': 15.8, 'wind_mean': 10.02, 'pressure_min': 1004.2, 'pressure_max': 1019.7, 'pressure_mean': 1011.82, 'visibility_min': 8.3, 'visibility_max': 12.6, 'visibility_mean': 10.06}
{'day': 6, 'temp_min': 15.5, 'temp_max': 26.2, 'temp_mean': 21.86, 'humidity_min': 53.1, 'humidity_max': 82.1, 'humidity_mean': 67.9, 'wind_min': 3.7, 'wind_max': 16.3, 'wind_mean': 9.9, 'pressure_min': 1003.6, 'pressure_max': 1019.0, 'pressure_mean': 1011.71, 'visibility_min': 8.1, 'visibility_max': 12.4, 'visibility_mean': 9.78}
{'day': 7, 'temp_min': 15.3, 'temp_max': 25.9, 'temp_mean': 21.17, 'humidity_min': 53.9, 'humidity_max': 80.8, 'humidity_mean': 65.53, 'wind_min': 3.7, 'wind_max': 16.2, 'wind_mean': 10.21, 'pressure_min': 998.1, 'pressure_max': 1017.9, 'pressure_mean': 1010.51, 'visibility_min': 9.0, 'visibility_max': 11.3, 'visibility_mean': 10.07}
{'day': 8, 'temp_min': 13.5, 'temp_max': 26.0, 'temp_mean': 20.9, 'humidity_min': 49.9, 'humidity_max': 83.3, 'humidity_mean': 67.29, 'wind_min': 3.8, 'wind_max': 16.9, 'wind_mean': 10.06, 'pressure_min': 1002.7, 'pressure_max': 1019.2, 'pressure_mean': 1010.48, 'visibility_min': 7.9, 'visibility_max': 11.6, 'visibility_mean': 9.63}
{'day': 9, 'temp_min': 14.3, 'temp_max': 27.1, 'temp_mean': 20.77, 'humidity_min': 51.8, 'humidity_max': 86.6, 'humidity_mean': 67.14, 'wind_min': 4.4, 'wind_max': 17.4, 'wind_mean': 10.09, 'pressure_min': 1000.2, 'pressure_max': 1022.8, 'pressure_mean': 1011.71, 'visibility_min': 8.1, 'visibility_max': 11.9, 'visibility_mean': 10.04}
{'day': 10, 'temp_min': 11.5, 'temp_max': 28.5, 'temp_mean': 21.62, 'humidity_min': 47.8, 'humidity_max': 80.1, 'humidity_mean': 66.4, 'wind_min': 4.5, 'wind_max': 17.0, 'wind_mean': 10.45, 'pressure_min': 1000.1, 'pressure_max': 1024.2, 'pressure_mean': 1011.67, 'visibility_min': 7.8, 'visibility_max': 12.5, 'visibility_mean': 10.1}

In [139]:
def daily_summary(matrix):
    summaries = []
    for i, row in enumerate(matrix):
        summary = {
            "day": i + 1,
            "min": np.nanmin(row),
            "max": np.nanmax(row),
            "mean": np.nanmean(row)
        }
        summaries.append(summary)
    return summaries
summaries = daily_summary(temp_matrix)

for s in summaries:
    print(f"Day {s['day']}: min={s['min']:.1f}, max={s['max']:.1f}, mean={s['mean']:.2f}")

Day 1: min=14.7, max=28.2, mean=21.26
Day 2: min=15.7, max=28.7, mean=21.26
Day 3: min=13.6, max=25.7, mean=21.30
Day 4: min=15.9, max=27.1, mean=21.43
Day 5: min=12.4, max=24.9, mean=21.54
Day 6: min=15.5, max=26.2, mean=21.86
Day 7: min=15.3, max=25.9, mean=21.17
Day 8: min=13.5, max=26.0, mean=20.90
Day 9: min=14.3, max=27.1, mean=20.77
Day 10: min=11.5, max=28.5, mean=21.62

## ✅ Submit your notebook once complete.
- Add comments where necessary